pipeline {
    agent any

    stages {
        stage('Prepare') {
            steps {
				sh 'sudo rm -rf UTN-devops-app'
                sh 'git clone https://github.com/AgusEDSA/UTN-devops-app.git || true'
                sh 'cd UTN-devops-app && sudo git checkout unidad-2'
                sh 'cd UTN-devops-app/myapp && sudo /usr/local/bin/composer install --no-scripts'
                sh 'sudo chmod 777 ./UTN-devops-app/myapp/bootstrap/cache/'
            }
        }
        stage('Build') {
            steps {
                sh 'find . -path ./UTN-devops-app/myapp/vendor -prune -o -name \\*.php -exec php -l "{}" \\;'
                retry(2) {
                    sh 'cd UTN-devops-app/myapp && sudo /usr/local/bin/composer update --no-scripts --prefer-dist'
                }
            }
        }
        stage('Test') {
            steps {
                sh './UTN-devops-app/myapp/vendor/bin/phpunit -c ./UTN-devops-app/myapp/phpunit.xml'
            }
        }
    }
}
